# Assignment 1



### NAME   
#### Thallapally Nimisha

### RollNo  
#### CS22B1082

### Date  
#### 20/01/2025


### Question 1 

### Do not use inbuilt functions for perceptron.

### Implement the Perceptron algorithm from scratch in Python
- Initialize the weights with [0 0 0] and a learning rate of 0.0001.
- For each iteration, calculate the output of the Perceptron for each input in the training set.
- Use MSE to computer the error for all samples
- Update the weights using the gradient descent procedure.
- Repeat the above steps until the Perceptron converges or a maximum number of iterations is reached.
- Test the trained Perceptron on a separate test set, explain how you came up with the test set.
- Use the step function as an  activation function in the output layer

- Use the IRIS Dataset for the above, considering all four features: sepal length, sepal width, petal length, and petal width, but only two classes -  Setosa, and Versicolor.  Drop the feature vectors of the other class. 

In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [76]:
# Load the iris dataset
df = pd.read_csv('iris.csv')

# Filter for Iris-setosa and Iris-virginica
df = df[(df['Species'] == 'Iris-setosa') | (df['Species'] == 'Iris-versicolor')]

# Create features and labels
data = df[['PetalLengthCm', 'PetalWidthCm' ,'SepalLengthCm','SepalWidthCm']].values
y = df['Species'].values

# Create an array similar to 'data'
# Map the species to 0 and 1
y_mapped = np.where(y == 'Iris-setosa', 0, 1)


In [77]:
data

array([[1.4, 0.2, 5.1, 3.5],
       [1.4, 0.2, 4.9, 3. ],
       [1.3, 0.2, 4.7, 3.2],
       [1.5, 0.2, 4.6, 3.1],
       [1.4, 0.2, 5. , 3.6],
       [1.7, 0.4, 5.4, 3.9],
       [1.4, 0.3, 4.6, 3.4],
       [1.5, 0.2, 5. , 3.4],
       [1.4, 0.2, 4.4, 2.9],
       [1.5, 0.1, 4.9, 3.1],
       [1.5, 0.2, 5.4, 3.7],
       [1.6, 0.2, 4.8, 3.4],
       [1.4, 0.1, 4.8, 3. ],
       [1.1, 0.1, 4.3, 3. ],
       [1.2, 0.2, 5.8, 4. ],
       [1.5, 0.4, 5.7, 4.4],
       [1.3, 0.4, 5.4, 3.9],
       [1.4, 0.3, 5.1, 3.5],
       [1.7, 0.3, 5.7, 3.8],
       [1.5, 0.3, 5.1, 3.8],
       [1.7, 0.2, 5.4, 3.4],
       [1.5, 0.4, 5.1, 3.7],
       [1. , 0.2, 4.6, 3.6],
       [1.7, 0.5, 5.1, 3.3],
       [1.9, 0.2, 4.8, 3.4],
       [1.6, 0.2, 5. , 3. ],
       [1.6, 0.4, 5. , 3.4],
       [1.5, 0.2, 5.2, 3.5],
       [1.4, 0.2, 5.2, 3.4],
       [1.6, 0.2, 4.7, 3.2],
       [1.6, 0.2, 4.8, 3.1],
       [1.5, 0.4, 5.4, 3.4],
       [1.5, 0.1, 5.2, 4.1],
       [1.4, 0.2, 5.5, 4.2],
       [1.5, 0

In [78]:
y_mapped

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Append Bias term 1

In [79]:
new_column = np.ones((data.shape[0], 1))
X = np.hstack((data, new_column))

In [80]:
X

array([[1.4, 0.2, 5.1, 3.5, 1. ],
       [1.4, 0.2, 4.9, 3. , 1. ],
       [1.3, 0.2, 4.7, 3.2, 1. ],
       [1.5, 0.2, 4.6, 3.1, 1. ],
       [1.4, 0.2, 5. , 3.6, 1. ],
       [1.7, 0.4, 5.4, 3.9, 1. ],
       [1.4, 0.3, 4.6, 3.4, 1. ],
       [1.5, 0.2, 5. , 3.4, 1. ],
       [1.4, 0.2, 4.4, 2.9, 1. ],
       [1.5, 0.1, 4.9, 3.1, 1. ],
       [1.5, 0.2, 5.4, 3.7, 1. ],
       [1.6, 0.2, 4.8, 3.4, 1. ],
       [1.4, 0.1, 4.8, 3. , 1. ],
       [1.1, 0.1, 4.3, 3. , 1. ],
       [1.2, 0.2, 5.8, 4. , 1. ],
       [1.5, 0.4, 5.7, 4.4, 1. ],
       [1.3, 0.4, 5.4, 3.9, 1. ],
       [1.4, 0.3, 5.1, 3.5, 1. ],
       [1.7, 0.3, 5.7, 3.8, 1. ],
       [1.5, 0.3, 5.1, 3.8, 1. ],
       [1.7, 0.2, 5.4, 3.4, 1. ],
       [1.5, 0.4, 5.1, 3.7, 1. ],
       [1. , 0.2, 4.6, 3.6, 1. ],
       [1.7, 0.5, 5.1, 3.3, 1. ],
       [1.9, 0.2, 4.8, 3.4, 1. ],
       [1.6, 0.2, 5. , 3. , 1. ],
       [1.6, 0.4, 5. , 3.4, 1. ],
       [1.5, 0.2, 5.2, 3.5, 1. ],
       [1.4, 0.2, 5.2, 3.4, 1. ],
       [1.6, 0

### Train Test Split (80-20)

In [81]:
# Split Setosa and Virginica samples
setosa_samples = X[y_mapped == 0]
versicolor_samples = X[y_mapped == 1]

# Manually split each class into training (80%) and testing (20%)
setosa_train = setosa_samples[:int(0.8 * len(setosa_samples))]
setosa_test = setosa_samples[int(0.8 * len(setosa_samples)):]

versicolor_train = versicolor_samples[:int(0.8 * len(versicolor_samples))]
versicolor_test = versicolor_samples[int(0.8 * len(versicolor_samples)):]

# Concatenate the corresponding training and testing sets
X_train = np.vstack((setosa_train, versicolor_train))
y_train = np.hstack((np.zeros(len(setosa_train)), np.ones(len(versicolor_train))))

X_test = np.vstack((setosa_test, versicolor_test))
y_test = np.hstack((np.zeros(len(setosa_test)), np.ones(len(versicolor_test))))

### Perceptron Algorithm

In [82]:
def perceptron_train(X_train, y_train, learning_rate=0.0001, max_iter=1000):
    weights = np.zeros(X.shape[1]) # Initialize weights (including bias) with 4 elements (1 for bias + 3 features)
    for epoch in range(max_iter):
        total_error = 0
        for i in range(len(X_train)):
            xi = X_train[i]
            yi = y_train[i]
            # Perceptron output using step function
            output = np.dot(xi, weights) >= 0  # Step function (output = 1 if >= 0, else 0)
            error = yi - output  # MSE error for this sample
            weights += learning_rate * error * xi  # Gradient descent update
            total_error += error**2  
        if total_error == 0:
            print(f"Converged after {epoch+1} iterations.")
            break
    return weights

### Perceptron Training

In [83]:
weights = perceptron_train(X_train, y_train)

Converged after 4 iterations.


In [84]:
weights

array([ 0.00052,  0.00022, -0.00013, -0.00041, -0.0001 ])

### Perceptron testing

In [85]:
def perceptron_predict(X, weights):
    return np.dot(X, weights) >= 0  # Step function prediction

# Test the perceptron on the test set
y_pred_test = perceptron_predict(X_test, weights)
y_pred_train = perceptron_predict(X_train, weights)

### Accuracy of training and testing

In [86]:
train_accuracy = np.mean(y_pred_train == y_train) * 100
print(f"Accuracy on the training set: {train_accuracy:.2f}%")

test_accuracy = np.mean(y_pred_test == y_test) * 100
print(f"Accuracy on the test set: {test_accuracy:.2f}%")

Accuracy on the training set: 100.00%
Accuracy on the test set: 100.00%
